#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i 's/.*listen\s*80.*/listen 80;/g' /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
