#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

sudo apt-get update
sudo apt-get -y install nginx

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo nginx -t

sudo service nginx restart
