#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo sed -i '/^server {/a \
    location /redirect_me {\
        return 301 https://www.example.com/destination;\
    }' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
