#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '30i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
