#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy

cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 531196-web-01 100.26.246.41:80 check
    server 531196-web-02 54.166.60.69:80 check
EOF

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy restart
